create table if not exists public.jawnix_settings (
  workspace_id text primary key,
  default_rate numeric(12, 6) not null default 0.0015,
  invoice_counter integer not null default 1 check (invoice_counter > 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.jawnix_leads (
  workspace_id text not null,
  id bigint generated by default as identity,
  date date not null,
  client text not null check (length(trim(client)) > 0),
  email text not null default '',
  leads integer not null check (leads > 0),
  rate numeric(12, 6) not null check (rate > 0),
  amount numeric(12, 2) generated always as (round(leads::numeric * rate, 2)) stored,
  created_at timestamptz not null default now(),
  primary key (workspace_id, id)
);

create table if not exists public.jawnix_invoice_voids (
  workspace_id text not null,
  week_start date not null,
  client text not null check (length(trim(client)) > 0),
  voided_at timestamptz not null default now(),
  primary key (workspace_id, week_start, client)
);

create table if not exists public.jawnix_invoice_records (
  workspace_id text not null,
  week_start date not null,
  client text not null check (length(trim(client)) > 0),
  invoice_num text not null check (length(trim(invoice_num)) > 0),
  checkout_session_id text not null default '',
  checkout_url text not null default '',
  pdf_filename text not null default '',
  total_due numeric(12, 2) not null default 0,
  payment_status text not null default 'unpaid' check (payment_status in ('paid', 'unpaid', 'expired', 'no_payment_required')),
  paid_at timestamptz,
  generated_at timestamptz not null default now(),
  voided_at timestamptz,
  primary key (workspace_id, week_start, client, invoice_num)
);

alter table public.jawnix_invoice_records
  add column if not exists payment_status text not null default 'unpaid'
    check (payment_status in ('paid', 'unpaid', 'expired', 'no_payment_required')),
  add column if not exists paid_at timestamptz;

do $$
declare
  constraint_name text;
begin
  for constraint_name in
    select con.conname
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
    where nsp.nspname = 'public'
      and rel.relname = 'jawnix_invoice_records'
      and con.contype = 'c'
      and pg_get_constraintdef(con.oid) like '%payment_status%'
  loop
    execute format('alter table public.jawnix_invoice_records drop constraint if exists %I', constraint_name);
  end loop;
end $$;

alter table public.jawnix_invoice_records
  drop constraint if exists jawnix_invoice_records_payment_status_check,
  add constraint jawnix_invoice_records_payment_status_check
    check (payment_status in ('paid', 'unpaid', 'expired', 'no_payment_required'));

create table if not exists public.jawnix_expenses (
  workspace_id text not null,
  id bigint generated by default as identity,
  category text not null default '',
  vendor text not null default '',
  expense_date date not null,
  billing_cycle text not null default '',
  notes text not null default '',
  amount numeric(12, 2) not null check (amount >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (workspace_id, id)
);

create table if not exists public.jawnix_misc_income (
  workspace_id text not null,
  id bigint generated by default as identity,
  income_date date not null,
  notes text not null default '',
  amount numeric(12, 2) not null check (amount >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (workspace_id, id)
);

do $$
begin
  if to_regclass('public.jawnix_weekly_financials') is not null then
    insert into public.jawnix_expenses (
      workspace_id,
      category,
      vendor,
      expense_date,
      billing_cycle,
      notes,
      amount,
      created_at,
      updated_at
    )
    select
      wf.workspace_id,
      'Lead costs',
      '',
      wf.week_start,
      'Migrated weekly lead costs',
      wf.notes,
      wf.lead_costs,
      coalesce(wf.updated_at, now()),
      coalesce(wf.updated_at, now())
    from public.jawnix_weekly_financials wf
    where wf.lead_costs > 0
      and not exists (
        select 1
        from public.jawnix_expenses e
        where e.workspace_id = wf.workspace_id
          and e.expense_date = wf.week_start
          and e.category = 'Lead costs'
          and e.billing_cycle = 'Migrated weekly lead costs'
          and e.amount = wf.lead_costs
          and e.notes = wf.notes
      );
  end if;
end $$;

create index if not exists jawnix_leads_workspace_date_idx
  on public.jawnix_leads (workspace_id, date);

create index if not exists jawnix_leads_workspace_client_idx
  on public.jawnix_leads (workspace_id, client);

create index if not exists jawnix_invoice_records_workspace_week_client_idx
  on public.jawnix_invoice_records (workspace_id, week_start, client);

create index if not exists jawnix_invoice_records_workspace_checkout_session_idx
  on public.jawnix_invoice_records (workspace_id, checkout_session_id);

create index if not exists jawnix_expenses_workspace_date_idx
  on public.jawnix_expenses (workspace_id, expense_date);

create index if not exists jawnix_misc_income_workspace_date_idx
  on public.jawnix_misc_income (workspace_id, income_date);

alter table public.jawnix_settings enable row level security;
alter table public.jawnix_leads enable row level security;
alter table public.jawnix_invoice_voids enable row level security;
alter table public.jawnix_invoice_records enable row level security;
alter table public.jawnix_expenses enable row level security;
alter table public.jawnix_misc_income enable row level security;

-- These policies are intended for a private/protected static deployment.
-- For a public app, add Supabase Auth and restrict each policy by user.
drop policy if exists "jawnix settings read" on public.jawnix_settings;
drop policy if exists "jawnix settings write" on public.jawnix_settings;
drop policy if exists "jawnix leads read" on public.jawnix_leads;
drop policy if exists "jawnix leads insert" on public.jawnix_leads;
drop policy if exists "jawnix leads update" on public.jawnix_leads;
drop policy if exists "jawnix leads delete" on public.jawnix_leads;
drop policy if exists "jawnix invoice voids read" on public.jawnix_invoice_voids;
drop policy if exists "jawnix invoice voids write" on public.jawnix_invoice_voids;
drop policy if exists "jawnix invoice records read" on public.jawnix_invoice_records;
drop policy if exists "jawnix invoice records write" on public.jawnix_invoice_records;
drop policy if exists "jawnix expenses read" on public.jawnix_expenses;
drop policy if exists "jawnix expenses write" on public.jawnix_expenses;
drop policy if exists "jawnix misc income read" on public.jawnix_misc_income;
drop policy if exists "jawnix misc income write" on public.jawnix_misc_income;

-- Customer portal migration. The tracker is no longer safe to expose with anon
-- policies once the public portal and its anon key are deployed.
create or replace function public.jawnix_is_admin()
returns boolean
language sql
stable
as $$
  select coalesce(auth.jwt() -> 'app_metadata' ->> 'jawnix_role', '') = 'admin';
$$;

create table if not exists public.jawnix_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null default '',
  first_name text not null default '',
  last_name text not null default '',
  phone text not null default '',
  licensed_states text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint jawnix_profiles_licensed_states_check check (
    licensed_states <@ array[
      'AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY','DC'
    ]::text[]
  )
);

create table if not exists public.jawnix_lead_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lead_count integer not null check (lead_count > 0),
  states_snapshot text[] not null default '{}',
  status text not null default 'pending' check (status in ('pending', 'fulfilled')),
  created_at timestamptz not null default now(),
  fulfilled_at timestamptz
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'jawnix_lead_requests_fulfillable_count_check'
      and conrelid = 'public.jawnix_lead_requests'::regclass
  ) then
    alter table public.jawnix_lead_requests
      add constraint jawnix_lead_requests_fulfillable_count_check
      check (lead_count between 1 and 2147483647)
      not valid;
  end if;
end $$;

create index if not exists jawnix_lead_requests_status_created_idx
  on public.jawnix_lead_requests (status, created_at);
create index if not exists jawnix_lead_requests_user_created_idx
  on public.jawnix_lead_requests (user_id, created_at desc);

create or replace function public.jawnix_snapshot_states()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  select coalesce(licensed_states, '{}') into new.states_snapshot
  from public.jawnix_profiles
  where user_id = new.user_id;
  new.states_snapshot := coalesce(new.states_snapshot, '{}');
  return new;
end;
$$;

drop trigger if exists jawnix_snapshot_states_before_insert on public.jawnix_lead_requests;
create trigger jawnix_snapshot_states_before_insert
  before insert on public.jawnix_lead_requests
  for each row execute function public.jawnix_snapshot_states();

alter table public.jawnix_leads add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.jawnix_invoice_records add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.jawnix_invoice_records add column if not exists pdf_path text not null default '';
create index if not exists jawnix_leads_user_id_idx on public.jawnix_leads (user_id);
create index if not exists jawnix_invoice_records_user_id_idx on public.jawnix_invoice_records (user_id);

alter table public.jawnix_profiles enable row level security;
alter table public.jawnix_lead_requests enable row level security;
revoke all on public.jawnix_profiles, public.jawnix_lead_requests from anon;

drop policy if exists "jawnix settings read" on public.jawnix_settings;
drop policy if exists "jawnix settings write" on public.jawnix_settings;
drop policy if exists "jawnix leads read" on public.jawnix_leads;
drop policy if exists "jawnix leads insert" on public.jawnix_leads;
drop policy if exists "jawnix leads update" on public.jawnix_leads;
drop policy if exists "jawnix leads delete" on public.jawnix_leads;
drop policy if exists "jawnix invoice voids read" on public.jawnix_invoice_voids;
drop policy if exists "jawnix invoice voids write" on public.jawnix_invoice_voids;
drop policy if exists "jawnix invoice records read" on public.jawnix_invoice_records;
drop policy if exists "jawnix invoice records write" on public.jawnix_invoice_records;
drop policy if exists "jawnix expenses read" on public.jawnix_expenses;
drop policy if exists "jawnix expenses write" on public.jawnix_expenses;
drop policy if exists "jawnix misc income read" on public.jawnix_misc_income;
drop policy if exists "jawnix misc income write" on public.jawnix_misc_income;

drop policy if exists "jawnix settings admin" on public.jawnix_settings;
drop policy if exists "jawnix leads admin" on public.jawnix_leads;
drop policy if exists "jawnix invoice voids admin" on public.jawnix_invoice_voids;
drop policy if exists "jawnix invoice records admin" on public.jawnix_invoice_records;
drop policy if exists "jawnix expenses admin" on public.jawnix_expenses;
drop policy if exists "jawnix misc income admin" on public.jawnix_misc_income;
create policy "jawnix settings admin" on public.jawnix_settings for all to authenticated using (public.jawnix_is_admin()) with check (public.jawnix_is_admin());
create policy "jawnix leads admin" on public.jawnix_leads for all to authenticated using (public.jawnix_is_admin()) with check (public.jawnix_is_admin());
create policy "jawnix invoice voids admin" on public.jawnix_invoice_voids for all to authenticated using (public.jawnix_is_admin()) with check (public.jawnix_is_admin());
create policy "jawnix invoice records admin" on public.jawnix_invoice_records for all to authenticated using (public.jawnix_is_admin()) with check (public.jawnix_is_admin());
create policy "jawnix expenses admin" on public.jawnix_expenses for all to authenticated using (public.jawnix_is_admin()) with check (public.jawnix_is_admin());
create policy "jawnix misc income admin" on public.jawnix_misc_income for all to authenticated using (public.jawnix_is_admin()) with check (public.jawnix_is_admin());

revoke all on public.jawnix_settings, public.jawnix_leads, public.jawnix_invoice_voids, public.jawnix_invoice_records, public.jawnix_expenses, public.jawnix_misc_income from anon;

do $$
begin
  if to_regclass('public.jawnix_weekly_financials') is not null then
    execute 'drop policy if exists "jawnix weekly financials read" on public.jawnix_weekly_financials';
    execute 'drop policy if exists "jawnix weekly financials write" on public.jawnix_weekly_financials';
    execute 'revoke all on public.jawnix_weekly_financials from anon';
  end if;
end $$;

drop policy if exists "jawnix profiles own select" on public.jawnix_profiles;
drop policy if exists "jawnix profiles own insert" on public.jawnix_profiles;
drop policy if exists "jawnix profiles own update" on public.jawnix_profiles;
drop policy if exists "jawnix requests own select" on public.jawnix_lead_requests;
drop policy if exists "jawnix requests own insert" on public.jawnix_lead_requests;
drop policy if exists "jawnix requests own delete" on public.jawnix_lead_requests;
drop policy if exists "jawnix requests admin update" on public.jawnix_lead_requests;
drop policy if exists "jawnix customer invoice inbox" on public.jawnix_invoice_records;
create policy "jawnix profiles own select" on public.jawnix_profiles for select to authenticated using (user_id = auth.uid() or public.jawnix_is_admin());
create policy "jawnix profiles own insert" on public.jawnix_profiles for insert to authenticated with check (user_id = auth.uid() or public.jawnix_is_admin());
create policy "jawnix profiles own update" on public.jawnix_profiles for update to authenticated using (user_id = auth.uid() or public.jawnix_is_admin()) with check (user_id = auth.uid() or public.jawnix_is_admin());
create policy "jawnix requests own select" on public.jawnix_lead_requests for select to authenticated using (user_id = auth.uid() or public.jawnix_is_admin());
create policy "jawnix requests own insert" on public.jawnix_lead_requests for insert to authenticated with check (user_id = auth.uid() and status = 'pending');
create policy "jawnix requests own delete" on public.jawnix_lead_requests for delete to authenticated using (user_id = auth.uid() and status = 'pending');
create policy "jawnix requests admin update" on public.jawnix_lead_requests for update to authenticated using (public.jawnix_is_admin()) with check (public.jawnix_is_admin());
create policy "jawnix customer invoice inbox" on public.jawnix_invoice_records for select to authenticated using (user_id = auth.uid() and voided_at is null);

insert into storage.buckets (id, name, public)
values ('jawnix-invoices', 'jawnix-invoices', false)
on conflict (id) do nothing;
drop policy if exists "jawnix invoice storage admin" on storage.objects;
drop policy if exists "jawnix invoice storage customer read" on storage.objects;
create policy "jawnix invoice storage admin" on storage.objects for all to authenticated using (bucket_id = 'jawnix-invoices' and public.jawnix_is_admin()) with check (bucket_id = 'jawnix-invoices' and public.jawnix_is_admin());
create policy "jawnix invoice storage customer read" on storage.objects for select to authenticated using (bucket_id = 'jawnix-invoices' and (storage.foldername(name))[1] = auth.uid()::text);
