create table if not exists public.jawnix_settings (
  workspace_id text primary key,
  default_rate numeric(12, 6) not null default 0.0015,
  invoice_counter integer not null default 1 check (invoice_counter > 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.jawnix_leads (
  workspace_id text not null,
  id bigint generated by default as identity,
  date date not null,
  client text not null check (length(trim(client)) > 0),
  email text not null default '',
  leads integer not null check (leads > 0),
  rate numeric(12, 6) not null check (rate > 0),
  amount numeric(12, 2) generated always as (round(leads::numeric * rate, 2)) stored,
  created_at timestamptz not null default now(),
  primary key (workspace_id, id)
);

create index if not exists jawnix_leads_workspace_date_idx
  on public.jawnix_leads (workspace_id, date);

create index if not exists jawnix_leads_workspace_client_idx
  on public.jawnix_leads (workspace_id, client);

alter table public.jawnix_settings enable row level security;
alter table public.jawnix_leads enable row level security;

-- These policies are intended for a private/protected static deployment.
-- For a public app, add Supabase Auth and restrict each policy by user.
drop policy if exists "jawnix settings read" on public.jawnix_settings;
drop policy if exists "jawnix settings write" on public.jawnix_settings;
drop policy if exists "jawnix leads read" on public.jawnix_leads;
drop policy if exists "jawnix leads insert" on public.jawnix_leads;
drop policy if exists "jawnix leads update" on public.jawnix_leads;
drop policy if exists "jawnix leads delete" on public.jawnix_leads;

create policy "jawnix settings read"
  on public.jawnix_settings for select
  to anon
  using (true);

create policy "jawnix settings write"
  on public.jawnix_settings for all
  to anon
  using (true)
  with check (true);

create policy "jawnix leads read"
  on public.jawnix_leads for select
  to anon
  using (true);

create policy "jawnix leads insert"
  on public.jawnix_leads for insert
  to anon
  with check (true);

create policy "jawnix leads update"
  on public.jawnix_leads for update
  to anon
  using (true)
  with check (true);

create policy "jawnix leads delete"
  on public.jawnix_leads for delete
  to anon
  using (true);
