create table if not exists public.jawnix_settings (
  workspace_id text primary key,
  default_rate numeric(12, 6) not null default 0.0015,
  invoice_counter integer not null default 1 check (invoice_counter > 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.jawnix_leads (
  workspace_id text not null,
  id bigint generated by default as identity,
  date date not null,
  client text not null check (length(trim(client)) > 0),
  email text not null default '',
  leads integer not null check (leads > 0),
  rate numeric(12, 6) not null check (rate > 0),
  amount numeric(12, 2) generated always as (round(leads::numeric * rate, 2)) stored,
  created_at timestamptz not null default now(),
  primary key (workspace_id, id)
);

create table if not exists public.jawnix_invoice_voids (
  workspace_id text not null,
  week_start date not null,
  client text not null check (length(trim(client)) > 0),
  voided_at timestamptz not null default now(),
  primary key (workspace_id, week_start, client)
);

create table if not exists public.jawnix_invoice_records (
  workspace_id text not null,
  week_start date not null,
  client text not null check (length(trim(client)) > 0),
  invoice_num text not null check (length(trim(invoice_num)) > 0),
  checkout_session_id text not null default '',
  checkout_url text not null default '',
  pdf_filename text not null default '',
  total_due numeric(12, 2) not null default 0,
  payment_status text not null default 'unpaid' check (payment_status in ('paid', 'unpaid', 'no_payment_required')),
  paid_at timestamptz,
  generated_at timestamptz not null default now(),
  voided_at timestamptz,
  primary key (workspace_id, week_start, client, invoice_num)
);

alter table public.jawnix_invoice_records
  add column if not exists payment_status text not null default 'unpaid'
    check (payment_status in ('paid', 'unpaid', 'no_payment_required')),
  add column if not exists paid_at timestamptz;

create table if not exists public.jawnix_expenses (
  workspace_id text not null,
  id bigint generated by default as identity,
  category text not null default '',
  vendor text not null default '',
  expense_date date not null,
  billing_cycle text not null default '',
  notes text not null default '',
  amount numeric(12, 2) not null check (amount >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (workspace_id, id)
);

create table if not exists public.jawnix_weekly_financials (
  workspace_id text not null,
  week_start date not null,
  lead_costs numeric(12, 2) not null default 0 check (lead_costs >= 0),
  notes text not null default '',
  updated_at timestamptz not null default now(),
  primary key (workspace_id, week_start)
);

create index if not exists jawnix_leads_workspace_date_idx
  on public.jawnix_leads (workspace_id, date);

create index if not exists jawnix_leads_workspace_client_idx
  on public.jawnix_leads (workspace_id, client);

create index if not exists jawnix_invoice_records_workspace_week_client_idx
  on public.jawnix_invoice_records (workspace_id, week_start, client);

create index if not exists jawnix_invoice_records_workspace_checkout_session_idx
  on public.jawnix_invoice_records (workspace_id, checkout_session_id);

create index if not exists jawnix_expenses_workspace_date_idx
  on public.jawnix_expenses (workspace_id, expense_date);

create index if not exists jawnix_weekly_financials_workspace_week_idx
  on public.jawnix_weekly_financials (workspace_id, week_start);

alter table public.jawnix_settings enable row level security;
alter table public.jawnix_leads enable row level security;
alter table public.jawnix_invoice_voids enable row level security;
alter table public.jawnix_invoice_records enable row level security;
alter table public.jawnix_expenses enable row level security;
alter table public.jawnix_weekly_financials enable row level security;

-- These policies are intended for a private/protected static deployment.
-- For a public app, add Supabase Auth and restrict each policy by user.
drop policy if exists "jawnix settings read" on public.jawnix_settings;
drop policy if exists "jawnix settings write" on public.jawnix_settings;
drop policy if exists "jawnix leads read" on public.jawnix_leads;
drop policy if exists "jawnix leads insert" on public.jawnix_leads;
drop policy if exists "jawnix leads update" on public.jawnix_leads;
drop policy if exists "jawnix leads delete" on public.jawnix_leads;
drop policy if exists "jawnix invoice voids read" on public.jawnix_invoice_voids;
drop policy if exists "jawnix invoice voids write" on public.jawnix_invoice_voids;
drop policy if exists "jawnix invoice records read" on public.jawnix_invoice_records;
drop policy if exists "jawnix invoice records write" on public.jawnix_invoice_records;
drop policy if exists "jawnix expenses read" on public.jawnix_expenses;
drop policy if exists "jawnix expenses write" on public.jawnix_expenses;
drop policy if exists "jawnix weekly financials read" on public.jawnix_weekly_financials;
drop policy if exists "jawnix weekly financials write" on public.jawnix_weekly_financials;

create policy "jawnix settings read"
  on public.jawnix_settings for select
  to anon
  using (true);

create policy "jawnix settings write"
  on public.jawnix_settings for all
  to anon
  using (true)
  with check (true);

create policy "jawnix leads read"
  on public.jawnix_leads for select
  to anon
  using (true);

create policy "jawnix leads insert"
  on public.jawnix_leads for insert
  to anon
  with check (true);

create policy "jawnix leads update"
  on public.jawnix_leads for update
  to anon
  using (true)
  with check (true);

create policy "jawnix leads delete"
  on public.jawnix_leads for delete
  to anon
  using (true);

create policy "jawnix invoice voids read"
  on public.jawnix_invoice_voids for select
  to anon
  using (true);

create policy "jawnix invoice voids write"
  on public.jawnix_invoice_voids for all
  to anon
  using (true)
  with check (true);

create policy "jawnix invoice records read"
  on public.jawnix_invoice_records for select
  to anon
  using (true);

create policy "jawnix invoice records write"
  on public.jawnix_invoice_records for all
  to anon
  using (true)
  with check (true);

create policy "jawnix expenses read"
  on public.jawnix_expenses for select
  to anon
  using (true);

create policy "jawnix expenses write"
  on public.jawnix_expenses for all
  to anon
  using (true)
  with check (true);

create policy "jawnix weekly financials read"
  on public.jawnix_weekly_financials for select
  to anon
  using (true);

create policy "jawnix weekly financials write"
  on public.jawnix_weekly_financials for all
  to anon
  using (true)
  with check (true);
